version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '22:00'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: eslint-plugin-testing-library
        versions:
          - 4.0.0
          - 4.0.1
          - 4.1.1
          - 4.1.2
      - dependency-name: husky
        versions:
          - 6.0.0
      - dependency-name: eslint-plugin-jest
        versions:
          - 24.3.1
      - dependency-name: '@typescript-eslint/parser'
        versions:
          - 4.18.0
      - dependency-name: eslint-config-prettier
        versions:
          - 8.0.0
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '22:00'
    open-pull-requests-limit: 10
